###############################
#      Report.ms app yml      #
###############################

lang: ru

Проект:
  Название: Автоматизация производства
  Описание: Система автоматизации производства, склада и планирования закупок
  Логотип: imgs/logo.svg
  FavIcon: imgs/favicon.svg
  Фон страницы логина: imgs/login_bg.png
  Текст первой ссылки: Основной сайт
  Url первой ссылки: https://report.ms
  Текст второй ссылки: Телеграм бот
  Url второй ссылки: https://t.me/automationProductionBot
  Использовать боты: Да
  Роль для пользователей: Клиент
  Приветствие бота при старте общения: Добро пожаловать! Здесь вы можете получить всю необходимую информацию о наших услугах, узнать о процессе строительства, увидеть примеры наших работ и задать вопрос. Используйте команду /open, чтобы открыть веб-интерфейс.
  # Боты:
  #   - @automationProductionBot:
  #     Тип: Telegram
  #     Токен: test

Роли:
  - Руководитель:
    Чат: Да
    База знаний: Да
    Администратор базы знаний: Да
  - Бригадир:
    Чат: Да
    База знаний: Да
  - Строитель:
    Чат: Да
    База знаний: Да
  - Конструктор:
    Чат: Да
    База знаний: Да
  - Менеджер:
    Чат: Да
    База знаний: Да
  - Клиент:
    Приветствия:
      - Добро пожаловать, Клиент!:
        Текст: Вы находитесь в системе управления производства, вы можете отслежитвать прогресс ваших заказов и ремонтов.
Справочники:
  - Типовые проекты:
    Наименование единицы справочника: Типовой проект
    Описание: Стандартные проектные решения, включающие в себя готовые схемы, чертежи и спецификации, которые могут быть использованы при планировании и реализации строительных проектов.
    Изображение в описании: imgs/typicly_projects.svg
    Иконка: book
    Поля:
      - Код:
        Заполнитель при пустом значении: ТП-XXXX
        Обязательно при создании: Да
        Обязательно при обновлении: Да
      - Работы:
        Тип: Таблица
        Справочник: Работы типового проекта
        Поле для обратной ссылки: Типовой проект
    Представления:
      - Типовые проекты - Администратор:
        Роль: Администратор
        Может создавать: Да
        Может открывать окно редактирования: Да
  - Работы типового проекта:
    Наименование единицы справочника: Работа типового проекта
    Поля:
      - Наименование:
        Заполнитель при пустом значении: Введите название...
        Обязательно при создании: Да
        Обязательно при обновлении: Да
      - Продолжительность:
        Тип: Продолжительность
        Заполнитель при пустом значении: Укажите продолжительность..
        Обязательно при создании: Да
        Обязательно при обновлении: Да
      - Типовой проект:
        Тип: Элемент справочника
        Справочник: Типовые проекты
  - Проекты:
    Наименование единицы справочника: Проект
    Описание: Строящийся дом на стапеле
    Иконка: home
    Изображение в описании: imgs/projects.svg
    Поля:
      - Прогресс:
        Тип: Прогресс
        Условие на просмотр: <ИСТИНА>
      - Клиент:
        Тип: Элемент справочника
        Справочник: Пользователи
        Ограничение выборки: '"Объект выборки (Пользователь): Роль" = "Роль: Клиент"'
        Условие скрытия: '"Текущий пользователь: Роль" = "Роль: Клиент"'
        Условие на просмотр: <ИСТИНА>
      - Стапель:
        Тип: Значение перечисления
        Перечисление: Стапель

    Представления:
      - Проекты - Администратор:
        Роль: Администратор
        Может открывать окно редактирования: Да
      - Проекты - Клиент:
        Роль: Клиент
        Может открывать окно редактирования: Да
        Правило выборки: '"Объект действия (Проект): Клиент" = "Текущий пользователь: Идентификатор"'

Плановые задачи:
  - Загрузка из файла:
    Описание: Создать типовую задачу на основе заполненного файла excel по шаблону
    Когда запускается: Пользователем
    # Доступно для ролей: [ Администратор ]
    Справочник: Типовые проекты
    С параметрами: Да
    Описание параметров: Создайте новый типовой проект на основе [этого шаблона](/public/tp_template.xlsx).
    Иконка кнопки: upload
    Иконка у описания параметров: file excel outline
    Параметры:
      - Название:
        Описание: С этим названием будет создан типовой проект
        Заполнитель при пустом значении: ТП-XXXX
        Обязательно при создании: Да
      - Файл:
        Тип: Файл
        Описание: На основе этого файла будет создан типовой проект
        Обязательно при создании: Да
    Шаги:
      - Создать фоновую задачу:
        Название фоновой задачи: Создание типового проекта на основе шаблона
        Python код: scripts/create_typicly_project.py
      - Показать сообщение:
        Текст сообщения: Загрузка файла началась

Перечисления:
  - Стапель:
    Значения:
      - Южный:
        Цвет: Оранжевый
      - Северный:
        Цвет: Синий
      - Восточный:
        Цвет: Оливковый